version: '3.9'
services:
  postgres:
    image: postgres:13.3
    environment:
      PGDATA: '/var/lib/postgresql/data/pgdata'
    volumes:
      - ./db/db_init:/docker-entrypoint-initdb.d
      - ./db:/var/lib/postgresql/data
      - ./db/init_files:/init_files
    ports:
      - '5432:5432'
    env_file:
      - .env
  backend:
    container_name: backend
    build:
      context: ./back/
      target: development
    volumes:
      - ./back/:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}
      - 9229:9229
    command: npm run start:dev
    env_file:
      - .env
    depends_on:
      - postgres